// Fixed builds used by the hand-calculated tests (the six round-1/2 builds). Kept separate from data/builds.js so the
// live build list can change without invalidating the worked examples in the tests.
window.WL = window.WL || {};
WL.TEST_BUILDS = [
  { key: 'aff_wrack_ds', short: 'Aff Wrack DS', name: 'Affliction – Wrack (DS Imp)', notes: 'fixture',
    talents: { suppression: 5, improvedCorruption: 5, malediction: 5, improvedDrains: 3, improvedBaneOfAgony: 2, pandemic: 3,
      malevolence: 5, nightfall: 2, siphonLife: 1, soulSiphon: 3, shadowMastery: 5, wrack: 1,
      demonicEmbrace: 5, felVitality: 3, demonicAegis: 2, demonicSacrifice: 1 },
    pet: null, sacrifice: 'imp', oil: 'spellstone',
    rotation: ['curseOfElements', 'shadowTrance', 'bane', 'corruption', 'siphonLife', 'immolate', 'wrack'] },
  { key: 'aff_wrack_succ', short: 'Aff Wrack Succubus', name: 'Affliction – Wrack (Succubus)', notes: 'fixture',
    talents: { suppression: 5, improvedCorruption: 5, malediction: 5, improvedDrains: 3, improvedBaneOfAgony: 2, pandemic: 3,
      malevolence: 5, nightfall: 2, siphonLife: 1, soulSiphon: 3, shadowMastery: 5, wrack: 1,
      unholyPower: 5, felVitality: 3, demonicEnergies: 2, improvedSayaad: 1 },
    pet: 'succubus', sacrifice: null, oil: 'spellstone',
    rotation: ['curseOfElements', 'shadowTrance', 'bane', 'corruption', 'siphonLife', 'immolate', 'wrack'] },
  { key: 'destro_incin_ds', short: 'Destro Incinerate DS', name: 'Destruction – Incinerate (DS Succubus)', notes: 'fixture',
    talents: { suppression: 5, improvedCorruption: 2, demonicEmbrace: 5, felVitality: 3, demonicAegis: 2, demonicSacrifice: 1,
      bane: 5, cataclysm: 3, aftermath: 5, ruin: 5, shadowburn: 1, agonizingFlames: 3, conflagrate: 1,
      baneOfHavoc: 1, fireAndBrimstone: 3, shadowAndFlame: 5, incinerate: 1 },
    pet: null, sacrifice: 'succubus', oil: 'firestone',
    rotation: ['curseOfElements', 'bane', 'immolate', 'conflagrate', 'shadowburn', 'corruption', 'incinerate'] },
  { key: 'destro_incin_aff', short: 'Destro Incinerate Imp', name: 'Destruction – Incinerate (Affliction, Imp)', notes: 'fixture',
    talents: { suppression: 5, improvedCorruption: 5, malediction: 5, improvedBaneOfAgony: 2, pandemic: 1,
      bane: 5, cataclysm: 3, aftermath: 5, ruin: 5, shadowburn: 1, agonizingFlames: 3, conflagrate: 1,
      baneOfHavoc: 1, fireAndBrimstone: 3, shadowAndFlame: 5, incinerate: 1 },
    pet: 'imp', sacrifice: null, oil: 'firestone',
    rotation: ['curseOfElements', 'bane', 'immolate', 'conflagrate', 'shadowburn', 'corruption', 'incinerate'] },
  { key: 'ds_ruin_sb', short: 'Destro Shadow Bolt DS', name: 'Destruction – Shadow Bolt (DS Imp / Ruin)', notes: 'fixture',
    talents: { suppression: 5, improvedCorruption: 5, demonicEmbrace: 5, felVitality: 3, demonicAegis: 2, demonicSacrifice: 1,
      improvedShadowBolt: 5, bane: 5, cataclysm: 3, aftermath: 2, ruin: 5, shadowburn: 1,
      agonizingFlames: 3, conflagrate: 1, shadowAndFlame: 5 },
    pet: null, sacrifice: 'imp', oil: 'spellstone',
    rotation: ['curseOfElements', 'shadowTrance', 'bane', 'corruption', 'immolate', 'conflagrate', 'shadowburn', 'shadowBolt'] },
  { key: 'demo_pact_succ', short: 'Demo Pact Shadow Bolt', name: 'Demonology – Demonic Pact (Imp sac + Succubus)', notes: 'fixture',
    talents: { unholyPower: 5, felVitality: 3, demonicEnergies: 2, demonicSacrifice: 1, improvedSayaad: 3, masterSummoner: 2,
      decimation: 2, demonicBrand: 3, soulLink: 1, demonicKnowledge: 3, masterDemonologist: 5, demonicPact: 1,
      improvedShadowBolt: 5, bane: 5, cataclysm: 3, aftermath: 2, ruin: 5 },
    pet: 'succubus', sacrifice: 'imp', oil: 'spellstone',
    rotation: ['curseOfElements', 'bane', 'corruption', 'immolate', 'soulFire', 'shadowBolt'] },
];
