# Generates data/tooltips.js from the archived Wowhead raw file (research/raw/wowhead_forever_talents-classic_dv27.js):
#   WL.TALENT_TEXT[talentKey] = [rank1 text, rank2 text, ...]
#   WL.SPELL_TEXT[spellId]    = tooltip text
# Usage: powershell -ExecutionPolicy Bypass -File tools\gen-tooltips.ps1
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$lines = [IO.File]::ReadAllLines("$root\research\raw\wowhead_forever_talents-classic_dv27.js")
function JsonArg($line) { $a = $line.IndexOf('{'); $b = $line.LastIndexOf('}'); return $line.Substring($a, $b - $a + 1) }
Add-Type -AssemblyName System.Web.Extensions
$ser = New-Object System.Web.Script.Serialization.JavaScriptSerializer
$ser.MaxJsonLength = 100MB
$calc = $ser.DeserializeObject((JsonArg $lines[0]))
$spells = $ser.DeserializeObject((JsonArg $lines[1]))

function Clean([string]$s) {
  $s = [regex]::Replace($s, '<!--.*?-->', '')
  $s = [regex]::Replace($s, '<br\s*/?>', "`n")
  $s = [regex]::Replace($s, '<dfn[^>]*>(.*?)</dfn>', '$1')
  $s = [regex]::Replace($s, '<[^>]+>', '')
  return [System.Web.HttpUtility]::HtmlDecode($s).Trim()
}
function Js([string]$s) { return ($ser.Serialize($s)) }

# Talents: map Wowhead talent id -> our key via data/talents.js
$tal = [IO.File]::ReadAllText("$root\data\talents.js")
$keyByWid = @{}
foreach ($m in [regex]::Matches($tal, "key: '(\w+)',\s*tree: '\w+', wid: (\d+)")) { $keyByWid[$m.Groups[2].Value] = $m.Groups[1].Value }
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('// GENERATED by tools/gen-tooltips.ps1 from research/raw/wowhead_forever_talents-classic_dv27.js — do not edit by hand.')
[void]$out.AppendLine('window.WL = window.WL || {};')
[void]$out.AppendLine('WL.TALENT_TEXT = {')
$n = 0
foreach ($tree in '301', '302', '303') {
  foreach ($t in $calc['talents'][$tree].Values) {
    $key = $keyByWid["$($t['id'])"]
    if (-not $key) { continue }
    $ranks = @()
    foreach ($r in ($t['descriptions'].Keys | Sort-Object { [int]$_ })) { $ranks += (Js (Clean $t['descriptions'][$r])) }
    [void]$out.AppendLine("  $key`: [" + ($ranks -join ', ') + '],')
    $n++
  }
}
[void]$out.AppendLine('};')
# Spells: every spell id used by data/spells.js, data/races.js and the pet spells in data/config.js
$ids = @()
foreach ($f in 'spells.js', 'races.js', 'config.js') { foreach ($m in [regex]::Matches([IO.File]::ReadAllText("$root\data\$f"), "id: (\d+)")) { $ids += $m.Groups[1].Value } }
[void]$out.AppendLine('WL.SPELL_TEXT = {')
# Spells whose tooltip changed after the archive was taken (2026-09-23). Text copied from the live Wowhead Forever
# spell page; the reason is in docs/01_SOURCES.md (S12) and docs/03_BUILD_LOG.md.
$override = @{
  '1259821' = 'Your next 3 damaging abilities have their Mana cost reduced by 10% and deal 10% more damage.'   # Eureka!, beta build 2026-09-24
  '20355' = "Attacks and spells used against you have a chance of restoring 59 of the attacker's mana. Lasts 40 sec."   # Judgement of Wisdom R3 debuff text (live Wowhead)
  # Trainer ranks (round 42): not in the archive. Damage = Wowhead Effect Value - 1 (SPELLVALUES.md); Shadow Bolt R9
  # 237 to 265 = the in-game range reported by the user (the Wowhead tooltip's 246 to 274 is wrong).
  '11661' = 'Sends a shadowy bolt at the enemy, causing 237 to 265 Shadow damage (+85.7% of Spell Power).'
  '11668' = 'Burns the enemy for 146 Fire damage (+20% of Spell Power) and then an additional 260 Fire damage (+65% of Spell Power) over 15 sec.'
  '11672' = 'Corrupts the target, causing 342 Shadow damage (+120% of Spell Power) over 18 sec.'
  # Shadow Bolt Rank 2 (round 57): Effect Value 26 - 1 = 25 (the Wowhead tooltip says 25 to 31).
  '695' = 'Sends a shadowy bolt at the enemy, causing 25 Shadow damage (+62.9% of Spell Power).'
}
$s = 0; $missing = @(); $o = 0
foreach ($id in ($ids | Select-Object -Unique)) {
  if ($override.ContainsKey($id)) { [void]$out.AppendLine("  $id`: " + (Js $override[$id]) + ','); $s++; $o++ }
  elseif ($spells.ContainsKey($id)) { [void]$out.AppendLine("  $id`: " + (Js (Clean $spells[$id]['description_enus'])) + ','); $s++ } else { $missing += $id }
}
[void]$out.AppendLine('};')
[IO.File]::WriteAllText("$root\data\tooltips.js", $out.ToString(), (New-Object Text.UTF8Encoding $false))
"talents: $n, spells: $s (overridden: $o), not in raw file: $($missing -join ',')"
