# Rebuilds data/icons.js (all icons embedded as data URIs so the page needs no external images).
# Icon names come from the archived Wowhead raw file wherever an ID exists:
#   spells   -> data/spells.js `id`            -> raw spell data "icon"
#   talents  -> data/talents.js `wid`          -> raw talent data "icon"
#   buffs / debuffs -> data/config.js `id`     -> raw spell data "icon"
# plus a small fixed list (pets, races, tree headers, racials, and icons that have no single spell ID).
# Images are downloaded once from https://wow.zamimg.com/images/wow/icons/medium/<name>.jpg into research/icons/.
# Usage: powershell -ExecutionPolicy Bypass -File tools\gen-icons.ps1
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$raw = [IO.File]::ReadAllText("$root\research\raw\wowhead_forever_talents-classic_dv27.js")
$dir = "$root\research\icons"; New-Item -ItemType Directory -Force $dir | Out-Null
function SpellIcon($id) { $m = [regex]::Match($raw, '"' + $id + '":\{"name_enus":"[^"]*","icon":"([^"]+)"'); if ($m.Success) { $m.Groups[1].Value } else { $null } }
function TalentIcon($wid) { $m = [regex]::Match($raw, '"id":' + $wid + ',"row":\d+,"col":\d+,"icon":"([^"]+)"'); if ($m.Success) { $m.Groups[1].Value } else { $null } }

$map = [ordered]@{}
# 1. Spells (key: id) from data/spells.js
foreach ($m in [regex]::Matches([IO.File]::ReadAllText("$root\data\spells.js"), "(\w+):\s*\{\s*id:\s*(\d+)")) {
  $ic = SpellIcon $m.Groups[2].Value; if ($ic) { $map[$m.Groups[1].Value] = $ic }
}
# 2. Fixed entries (no single spell ID in our data, or not in the raw file)
$fixed = [ordered]@{
  bane = 'spell_shadow_curseofsargeras'; shadowTrance = 'spell_shadow_twilight'; demonicSacrifice = 'spell_shadow_psychicscream'
  touchOfTheGrave = 'spell_shadow_fingerofdeath'; firebolt = 'spell_fire_firebolt'; lashOfPain = 'spell_shadow_curse'
  pet_imp = 'spell_shadow_summonimp'; pet_succubus = 'spell_shadow_summonsuccubus'; pet_felhunter = 'spell_shadow_summonfelhunter'; pet_voidwalker = 'spell_shadow_summonvoidwalker'
  race_human = 'race_human_male'; race_gnome = 'race_gnome_male'; race_orc = 'race_orc_male'; race_undead = 'race_scourge_male'; race_troll = 'race_troll_male'
  tree_affliction = 'spell_shadow_deathcoil'; tree_demonology = 'spell_shadow_metamorphosis'; tree_destruction = 'spell_shadow_rainoffire'
  racial_bloodFury = 'racial_orc_berserkerstrength'; racial_berserking = 'racial_troll_berserk'; racial_eureka = 'inv_gnometoy'
}
foreach ($k in $fixed.Keys) { if (-not $map.Contains($k)) { $map[$k] = $fixed[$k] } }
# 3. Talents
foreach ($m in [regex]::Matches([IO.File]::ReadAllText("$root\data\talents.js"), "key: '(\w+)',\s*tree: '\w+', wid: (\d+)")) {
  $ic = TalentIcon $m.Groups[2].Value; if ($ic) { $map['talent_' + $m.Groups[1].Value] = $ic }
}
# 4. Buffs and debuffs (config ids); Restorative Totems is a talent (spell 16187 is not in the raw spell data)
$cfg = [IO.File]::ReadAllText("$root\data\config.js")
$section = ''
foreach ($line in $cfg -split "`n") {
  if ($line -match '^\s{2}buffs:\s*\{') { $section = 'buff' } elseif ($line -match '^\s{2}debuffs:\s*\{') { $section = 'debuff' } elseif ($line -match '^\s{2}\},') { $section = '' }
  if ($section -and $line -match '^\s+(\w+)\s*:\s*\{ on: (?:true|false), id: (\d+)') {
    $ic = SpellIcon $Matches[2]; if (-not $ic -and $Matches[1] -eq 'restorativeTotems') { $ic = 'spell_nature_manaregentotem' }
    if (-not $ic -and $Matches[1] -eq 'judgementOfWisdom') { $ic = 'spell_holy_righteousnessaura' }   # Wowhead Forever tooltip icon (round 38)
    if ($ic) { $map["$($section)_$($Matches[1])"] = $ic }
  }
}
# 5. Consumables: icon name is given directly in data/consumables.js (from the Forever item XML <icon> field)
foreach ($m in [regex]::Matches([IO.File]::ReadAllText("$root\data\consumables.js"), "(\w+):\s*\{ on: (?:true|false), id: \d+, icon: '(\w+)'")) {
  $map['consumable_' + $m.Groups[1].Value] = $m.Groups[2].Value
}
# Download (once) and embed
$lines = @(); $fail = @()
foreach ($k in $map.Keys) {
  $f = "$dir\$($map[$k]).jpg"
  try {
    if (-not (Test-Path $f)) { Invoke-WebRequest -UseBasicParsing "https://wow.zamimg.com/images/wow/icons/medium/$($map[$k]).jpg" -OutFile $f }
    $lines += "  $k`: 'data:image/jpeg;base64,$([Convert]::ToBase64String([IO.File]::ReadAllBytes($f)))',"
  } catch { $fail += "$k($($map[$k]))" }
}
$js = "// GENERATED by tools/gen-icons.ps1 - Wowhead icons (wow.zamimg.com, 36 px) embedded as data URIs. Do not edit by hand.`r`nwindow.WL = window.WL || {};`r`nWL.ICONS = {`r`n" + ($lines -join "`r`n") + "`r`n};`r`n"
[IO.File]::WriteAllText("$root\data\icons.js", $js, (New-Object Text.UTF8Encoding $false))
"icons: $($lines.Count), failed: $($fail -join ',')"
